### ISSUE TITLE
Not seeing messages in conversation window when sending more than just text

### ISSUE THREAD

**Issue by AcharyaS97** [vidit135g/Replify-Messenger#1]
### DESCRIPTION
(Running on Samsung A70 with API 29)

When in a conversation and I try attaching a contact or a photo, it doesn't appear in my chat window as a message that I sent, but the other person does receive the message.

### STEPS
1. Open a conversation, 
2. Attach a contact, 
3a. Hit send.
3b. Take a photo, or attach a photo from the gallery,
4. Hit send.

### EXPECTED
A message bubble appears, right aligned in the conversation window, indicating that you sent a message with a contact or an image.

### OBSERVATIONS
The contact on the other side of the conversation receives the message but it doesn't appear as having been sent from you on your side. 

I'd be interested in digging in tackling this issue since it seems like the repo has not been updated in a few months.

**Comment by AcharyaS97** [comment]
Repo should have some indication that this project is a fork of the QkSms Android app with new branding.

**Comment by vidit135g** [comment]
I haven't been able to work on it from last few months due to a lot of workload. And yes mentioning more about the parent repo would be apt. Will update the readme as soon as possible. Thanks for reporting this 🙂.

**Comment by vidit135g** [comment]
> Repo should have some indication that this project is a fork of the QkSms Android app with new branding.

I have already given the credits to QKSMS in the Readme itself.
